language: php
sudo: false
services:
  - docker
cache:
  directories:
    - $HOME/.composer/cache
matrix:
  include:
  # PHP Supported versions: https://www.php.net/supported-versions.php
  - php: 7.3
  - php: 7.4
  # NOTE: These are intended to fail until the compose package
  # is updated to handle the tests (or lack thereof) correctly.
  fast_finish: true
before_install:
  - composer self-update
install:
  - composer install
script:
    - docker build -t mozilla-it/wiki .
# after_success:
#     - bash <(curl -s https://codecov.io/bash)
